persistence.repositoryFactory=eapli.aisafe.persistence.impl.jpa.JpaRepositoryFactory
persistence.persistenceUnit=eapli.aisafe
ui.menu.layout=horizontal

jakarta.persistence.schema-generation.database.action=none

jakarta.persistence.jdbc.driver=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.pool_size=3
